// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDti23XLh4WYVkaBgEKCk2F7s9KV8S12k',
    appId: '1:937465072379:web:898a05a31fcb5e459d7e5e',
    messagingSenderId: '937465072379',
    projectId: 'taskora-551f1',
    authDomain: 'taskora-551f1.firebaseapp.com',
    storageBucket: 'taskora-551f1.firebasestorage.app',
    measurementId: 'G-41RTCGDFPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBOrrZ2Kzy9AZjIYt0oZfbyC3mbna6uw',
    appId: '1:937465072379:android:f44f408430c3febe9d7e5e',
    messagingSenderId: '937465072379',
    projectId: 'taskora-551f1',
    storageBucket: 'taskora-551f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTnu-2-0sqKgLRJdj9iu38q6V3xqGZ7dI',
    appId: '1:937465072379:ios:4e83686029fd9fe19d7e5e',
    messagingSenderId: '937465072379',
    projectId: 'taskora-551f1',
    storageBucket: 'taskora-551f1.firebasestorage.app',
    iosBundleId: 'com.example.taskora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTnu-2-0sqKgLRJdj9iu38q6V3xqGZ7dI',
    appId: '1:937465072379:ios:4e83686029fd9fe19d7e5e',
    messagingSenderId: '937465072379',
    projectId: 'taskora-551f1',
    storageBucket: 'taskora-551f1.firebasestorage.app',
    iosBundleId: 'com.example.taskora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDti23XLh4WYVkaBgEKCk2F7s9KV8S12k',
    appId: '1:937465072379:web:75db6a2d3c11bd0e9d7e5e',
    messagingSenderId: '937465072379',
    projectId: 'taskora-551f1',
    authDomain: 'taskora-551f1.firebaseapp.com',
    storageBucket: 'taskora-551f1.firebasestorage.app',
    measurementId: 'G-VZ53NMZQHC',
  );
}
